### ISSUE TITLE
How do I add this?

### ISSUE THREAD

**Issue by Mike4l6** [ImagicalGamer/SkyWarsV3#1]
Its a simple question I know. But I only add phar files.Alternative: give me a download link for the phar file. Pleaase

**Comment by ImagicalGamer** [comment]
This doesn't have world restore yet so not much can be done with it. I will work more on it tonight. Download the ZIP and go to pmt.mcpe.me and you can compile it there.

**Comment by MateiGamingYTB** [comment]
crashing

**Comment by MateiGamingYTB** [comment]
phar crashing

**Comment by ImagicalGamer** [comment]
Ik, I said it's not fully operational. xD

**Comment by ImagicalGamer** [comment]
What was the crash script or errors?

**Comment by kaitododoyt** [comment]
is this man:

[Server thread/INFO]: Loading SkyWarsV3 v3.0.2
[19:18:17] [Server thread/CRITICAL]: ClassNotFoundException: "Class SkyWarsV3\SkyWarsV3 not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 115
[19:18:17] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by ImagicalGamer** [comment]
Ik the plugin isn't finished yet.

**Comment by kaitododoyt** [comment]
yeah, i download now for test and tell you the error :).

I have this Skywars plugin https://mega.nz/#!Wxsm3YDJ!txPa--bTdRRn-oi-Hi8s1rGco-x24OadxvTym-2a53E

This works but dont show sign correctly and dmap reset isn't implemented

**Comment by Mike4l6** [comment]
[20:58:36] [Server thread/CRITICAL]: ClassNotFoundException: "Class SkyWarsV3\SkyWarsV3 not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 131 - this a problem when I used the phar above.

**Comment by ImagicalGamer** [comment]
If it was a diff plugin nothin I can do, I'm working on this plugin slowly, I have other projects to focus on.

**Comment by Mike4l6** [comment]
Ok i understand I wish you good luck on your plugin. :D

**Comment by Mike4l6** [comment]
I more thing what are the commands?
